networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:1.21.5
    container_name: gitea
    restart: unless-stopped
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea/gitea.db
      - GITEA__server__DOMAIN=${GITEA_DOMAIN:-localhost}
      - GITEA__server__SSH_DOMAIN=${GITEA_DOMAIN:-localhost}
      - GITEA__server__ROOT_URL=http://${GITEA_DOMAIN:-localhost}:${GITEA_HTTP_PORT:-3000}/
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__SSH_PORT=22
      - GITEA__security__INSTALL_LOCK=${GITEA_INSTALL_LOCK:-false}
      - GITEA__service__DISABLE_REGISTRATION=${GITEA_DISABLE_REGISTRATION:-false}
      - GITEA__service__REQUIRE_SIGNIN_VIEW=${GITEA_REQUIRE_SIGNIN:-false}
      - GITEA__mailer__ENABLED=${GITEA_MAILER_ENABLED:-false}
      - GITEA__mailer__FROM=${GITEA_MAILER_FROM:-gitea@localhost}
      - GITEA__mailer__HOST=${GITEA_MAILER_HOST:-smtp.gmail.com:587}
      - GITEA__mailer__USER=${GITEA_MAILER_USER:-}
      - GITEA__mailer__PASSWD=${GITEA_MAILER_PASSWD:-}
    networks:
      - gitea
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GITEA_HTTP_PORT:-3000}:3000"
      - "${GITEA_SSH_PORT:-222}:22"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # 선택사항: 리버스 프록시를 위한 nginx
  nginx:
    image: nginx:alpine
    container_name: gitea-nginx
    restart: unless-stopped
    depends_on:
      - gitea
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - gitea
    profiles:
      - nginx

# volumes:
#   gitea-data:
#     driver: local